name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: |
            ./app/package-lock.json
            ./server/package-lock.json

      - name: Install dependencies (app)
        working-directory: app
        run: npm ci

      - name: Install dependencies (server)
        working-directory: server
        run: npm ci

      - name: Generate Prisma client
        working-directory: server
        run: npm run generate

      - name: Build (server)
        working-directory: server
        run: npm run build

      - name: Build (app)
        working-directory: app
        run: npm run build

      - name: Require clean working directory
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job."
            exit 1
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package-name:
          - app
          - server

    defaults:
      run:
        working-directory: ${{ matrix.package-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: ./${{ matrix.package-name }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
